# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 506d032f81f91b8cc9ccbfefe87251a83d65734afbe119f9d420969cc952d207427cabf8c42702c1b70b1ea0a8b5e2a91411babee6487485ca691bcb34b94ed2

test:
  secret_key_base: 638e1d8472ef7c3331cc136c57536c625b2dd3f6c49f82c321eb1dfba78a9f370b4f336df675322ca2ff9493c6aa66eaf4bfcf0a2a2861c9a70a7e4797781ad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
